a=int(input("enter runs scored by first player : "))
b=int(input("enter runs scored by second player : "))
c=int(input("enter runs scored by third player : "))
print("strike rate of first : ",a*100//60)
print("strike rate of second : ",b*100//60)
print("strike rate of third : ",c*100//60)
print("runs scored by player first if he plays 60 balls more : ",a*2)
print("runs scored by player second if he plays 60 balls more : ",b*2)
print("runs scored by player third if he plays 60 balls more : ",c*2)
print("maximum sixes by first player : ",a//6)
print("maximum sixes by second player : ",b//6)
print("maximum sixes by third player : ",c//6)
